# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e787f0b587f5972dcbbb25a7b4e7e7eaa31f8d9035a794f641be9970dfe3bc2368c000a295c093803a43037fcad1ee4f633b22885763172ce2a62b4cee95de0f

test:
  secret_key_base: 4eb49ac0266121048ae42d8a5d03548ac356009abf8085ba1561b0c66b1571243a5f0adb538ade4ae0db6b65777fd7ee91a67e477828f5a77ad4208396b0ec9a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
